name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Specify the service name"
        type: string
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Check if service name is provided
        if: ${{ github.event.inputs.service_name == '' }}
        run: |
          echo "No service name provided. Please provide a service name."
          exit 1 # Exit with an error code
      
      - name: Print service name
        if: ${{ github.event.inputs.service_name != '' }}
        run: |
          echo "Service name is provided: ${{ github.event.inputs.service_name }}"
